//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ApiExamenLib.WsExamenApiRef {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsExamenSoap", Namespace="http://tempuri.org/")]
    public partial class WsExamen : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AgregarExamenOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarExamenOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarExamenOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarExamenOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsExamen() {
            this.Url = global::ApiExamenLib.Properties.Settings.Default.ApiExamenLib_WsExamenApiRef_WsExamen;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AgregarExamenCompletedEventHandler AgregarExamenCompleted;
        
        /// <remarks/>
        public event ActualizarExamenCompletedEventHandler ActualizarExamenCompleted;
        
        /// <remarks/>
        public event EliminarExamenCompletedEventHandler EliminarExamenCompleted;
        
        /// <remarks/>
        public event ConsultarExamenCompletedEventHandler ConsultarExamenCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarExamen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AgregarExamen(string nombre, string descripcion, out string errorMsg) {
            object[] results = this.Invoke("AgregarExamen", new object[] {
                        nombre,
                        descripcion});
            errorMsg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarExamenAsync(string nombre, string descripcion) {
            this.AgregarExamenAsync(nombre, descripcion, null);
        }
        
        /// <remarks/>
        public void AgregarExamenAsync(string nombre, string descripcion, object userState) {
            if ((this.AgregarExamenOperationCompleted == null)) {
                this.AgregarExamenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarExamenOperationCompleted);
            }
            this.InvokeAsync("AgregarExamen", new object[] {
                        nombre,
                        descripcion}, this.AgregarExamenOperationCompleted, userState);
        }
        
        private void OnAgregarExamenOperationCompleted(object arg) {
            if ((this.AgregarExamenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarExamenCompleted(this, new AgregarExamenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarExamen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarExamen(int id, string nombre, string descripcion, out string errorMsg) {
            object[] results = this.Invoke("ActualizarExamen", new object[] {
                        id,
                        nombre,
                        descripcion});
            errorMsg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarExamenAsync(int id, string nombre, string descripcion) {
            this.ActualizarExamenAsync(id, nombre, descripcion, null);
        }
        
        /// <remarks/>
        public void ActualizarExamenAsync(int id, string nombre, string descripcion, object userState) {
            if ((this.ActualizarExamenOperationCompleted == null)) {
                this.ActualizarExamenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarExamenOperationCompleted);
            }
            this.InvokeAsync("ActualizarExamen", new object[] {
                        id,
                        nombre,
                        descripcion}, this.ActualizarExamenOperationCompleted, userState);
        }
        
        private void OnActualizarExamenOperationCompleted(object arg) {
            if ((this.ActualizarExamenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarExamenCompleted(this, new ActualizarExamenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarExamen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarExamen(int id, out string errorMsg) {
            object[] results = this.Invoke("EliminarExamen", new object[] {
                        id});
            errorMsg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarExamenAsync(int id) {
            this.EliminarExamenAsync(id, null);
        }
        
        /// <remarks/>
        public void EliminarExamenAsync(int id, object userState) {
            if ((this.EliminarExamenOperationCompleted == null)) {
                this.EliminarExamenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarExamenOperationCompleted);
            }
            this.InvokeAsync("EliminarExamen", new object[] {
                        id}, this.EliminarExamenOperationCompleted, userState);
        }
        
        private void OnEliminarExamenOperationCompleted(object arg) {
            if ((this.EliminarExamenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarExamenCompleted(this, new EliminarExamenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarExamen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tblExamen[] ConsultarExamen(int id, string nombre, string descripcion) {
            object[] results = this.Invoke("ConsultarExamen", new object[] {
                        id,
                        nombre,
                        descripcion});
            return ((tblExamen[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarExamenAsync(int id, string nombre, string descripcion) {
            this.ConsultarExamenAsync(id, nombre, descripcion, null);
        }
        
        /// <remarks/>
        public void ConsultarExamenAsync(int id, string nombre, string descripcion, object userState) {
            if ((this.ConsultarExamenOperationCompleted == null)) {
                this.ConsultarExamenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarExamenOperationCompleted);
            }
            this.InvokeAsync("ConsultarExamen", new object[] {
                        id,
                        nombre,
                        descripcion}, this.ConsultarExamenOperationCompleted, userState);
        }
        
        private void OnConsultarExamenOperationCompleted(object arg) {
            if ((this.ConsultarExamenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarExamenCompleted(this, new ConsultarExamenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tblExamen {
        
        private int idExamenField;
        
        private string nombreField;
        
        private string descripcionField;
        
        /// <remarks/>
        public int idExamen {
            get {
                return this.idExamenField;
            }
            set {
                this.idExamenField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AgregarExamenCompletedEventHandler(object sender, AgregarExamenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarExamenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarExamenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ActualizarExamenCompletedEventHandler(object sender, ActualizarExamenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarExamenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarExamenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void EliminarExamenCompletedEventHandler(object sender, EliminarExamenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarExamenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarExamenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultarExamenCompletedEventHandler(object sender, ConsultarExamenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarExamenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarExamenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tblExamen[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tblExamen[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591